### ISSUE TITLE
All the Mods 3 Lite - 3.2.0 Simple server not downloading any mods

### ISSUE THREAD

**Issue by LuiizGoncallves** [AllTheMods/ATM-3#1001]
Ive been trying to get a ATM 3 lite server working and for every mod that it trys to download, this error shows up...

```
java.io.IOException: Request to https://cursemeta.dries007.net/256662/2833871.json was not successful.
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType$downloadMods$1.accept(CursePackType.kt:203)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType$downloadMods$1.accept(CursePackType.kt:27)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.downloadMods(CursePackType.kt:183)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.postProcessing(CursePackType.kt:156)
        at atm.bloodworkxgaming.serverstarter.packtype.AbstractZipbasedPackType.installPack(AbstractZipbasedPackType.kt:32)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:152)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:195)
[14:54:52] [ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=248453, fileID=2785465)
```

and when I follow the link to the file it trys to request it seems that its using a deprecated API.

https://cursemeta.dries007.net/
Any way to fix this problem ;(

**Comment by Pelotrio** [comment]
Curseforge switched to a new api and because of this it completly breaks this method to download the mods for the server.

**Comment by LuiizGoncallves** [comment]
> Curseforge switched to a new api and because of this it completly breaks this method to download the mods for the server.

how to proceed then?
