### ISSUE TITLE
Failed to save chunk

### ISSUE THREAD

**Issue by ouroborus** [AllTheMods/ATM-3#221]
I had set up an enderman farm. When I turned it on, The server started throwing these errors:

    [23:07:05] [File IO Thread/ERROR]: Failed to save chunk
    java.util.ConcurrentModificationException: null
            at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_144]
            at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_144]
            at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:32) ~[fy.class:?]
            at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112) ~[gi.class:?]
            at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102) ~[gi.class:?]
            at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:238) ~[aye.class:?]
            at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:216) [aye.class:?]
            at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37) [bgx.class:?]
            at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30) [bgx.class:?]
            at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

Farm includes 8x resturbed spawners w/ 4x speed upgrade each (Extra Utilites 2), ender tether (Dark Utilities), diamond spikes (Cyclic), experience pylon (Cyclic), quantum tank (Quantum Storage), item collector (Cyclic), ender chest (Ender Storage).

The exceptions stopped when I turned off the spawners. I'm not sure which bit is actually causing this.

EDIT: This farm is in the Aroma1997 Mining Dimension (-6). These exceptions seem to only happen if I leave the dimension. When I return, they stop. I have the chunk the building is in chunkloaded. I also tried chunkloading a 5x5 area to account for the endermens' teleport range but no change.

**Comment by Boomflex** [comment]
Please update to latest version of the pack (v4.3)

This was to do with a chunk batching issue with Forge.

Should now be fixed.
