### ISSUE TITLE
Model Loader Crash

### ISSUE THREAD

**Issue by Asteroid1** [AllTheMods/ATM-3#643]
Keeps on crashing, it works for about 5-10 seconds when I join a world
https://gist.github.com/Asteroid1/bd5a6254695d9e293805d68458a91c5e
https://gist.github.com/Asteroid1/7ffddfcbad2407ca56a96436a9d8f50d
I tried looking for any duplicates (I couldn't find any), but I could easily be wrong.
Thank you

**Comment by MythixDino** [comment]
Since what I get is similar but for another block and only when accessing the chest with the corresponding item in it. This seems to be a rendering issue.

-- Item being rendered --
Details:
	Item Type: mekanism.generators.common.item.ItemBlockGenerator@27dd9887
	Item Aux: 10
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:210)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at cpw.mods.ironchest.client.gui.chest.GUIChest.func_73863_a(GUIChest.java:100)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:648)

**Comment by DKnightADRI** [comment]
Seems to be a stencil table in your case.
And as @MythixDino mentioned before, this is a rendering issue. You can try to disable mods that interfere with model rendering like Optifine (if you have any - didn't find them on the first look)

-- Block model being tesselated --

Details:

	Block: tconstruct:tooltables[type=stenciltable]

	Block location: World: (519,70,4277), Chunk: (at 7,4,5 in 32,267; contains blocks 512,0,4272 to 527,255,4287), Region: (1,8; contains chunks 32,256 to 63,287, blocks 512,0,4096 to 1023,255,4607)

	Using AO: true

Stacktrace:

	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)

	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)



-- Block being tesselated --

Details:

	Block type: ID #2827 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.common.block.BlockToolTable)

	Block data value: 1 / 0x1 / 0b0001

	Block location: World: (519,70,4277), Chunk: (at 7,4,5 in 32,267; contains blocks 512,0,4272 to 527,255,4287), Region: (1,8; contains chunks 32,256 to 63,287, blocks 512,0,4096 to 1023,255,4607)

Stacktrace:

	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:69)

**Comment by FallenEagle1** [comment]
DKnightADRI has the right block pinned down for what is erroring out, a stencil table. One thing I'd add is update java. From the log, java 1.8.0_51 is being used. Latest is 1.8.0_171.

Optifine may help, but if you have cheats enabled to allow commands, since you have a couple seconds ingame you could use the /clear commands to remove it. Have the command typed out already and copied so you can just paste it and hit enter to try removing it.

**Comment by DKnightADRI** [comment]
If I'm not mistaken that Java version is the stupid thing that the twitch launcher automatically installs, try the legacy java launcher or swap the bin and lib folder in \Twitch\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51\ with the one @FallenEagle1 mentioned. Or you can change the path of course, but it changes itself back to normal if you relaunch it.

**Comment by SpeedSlider** [comment]
We recommend the old launcher with twitch set to use the jar launching method.

**Comment by SpeedSlider** [comment]
Additionally, this may be related to a forge issue we had with 5.9.8a

**Comment by Asteroid1** [comment]
Thank you guys for all the help, its working now
