### ISSUE TITLE
Extra Utilities Biome Marker crashes client when filling Refined storage pattern

### ISSUE THREAD

**Issue by ogradyjd** [AllTheMods/ATM-3#661]
If you need anything else from me on this, let me know.

## Expected Behavior
With the Refined Storage pattern grid open, you go into JEI and select Extra Utilities Biome marker so you can hit the plus sign and fill the pattern.

## Current Behavior
Hitting the plus sign to fill the pattern crashes the client.

## Possible Solution
I took a quick search around Extra Utilities issue list and hit google with some variations of the issue.  Nothing.  From the stacktrace, it looks like it's possibly an Extra Utilities -> Forge client issue?  The exception message seems to indicate that the client is expecting a value for a java short primitive, and it's getting something larger (probably an integer).  I don't know anything about the Forge and modding APIs, so that's my best guess based on the behaviour and the logs.

Just for kicks, I cheated in a blank biome marker and it works just fine, soooo... crafting recipe is the problem?

## Steps to Reproduce
1. Open up a Refined Storage pattern grid.
2. Now search in JEI for biome marker. 
3. Select any of them (even the base craftable version) and hit the plus (+) sign to copy the pattern to the pattern grid.
4.  Go put on some water and wait for your tea to cool, because this pack takes a very long time to reload.

## Log
The pertinent part of the log isn't that big:
```
[17:28:09] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 36%
[17:28:14] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 36%
[17:28:19] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 36%
[17:28:24] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 36%
[17:28:29] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 37%
[17:28:34] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 37%
[17:28:39] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 37%
[17:28:44] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 38%
[17:28:49] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 38%
[17:28:54] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 38%
[17:28:55] [ThaumicJEI Aspect Cache/ERROR]: Invalid BasicBlock. type: 0, meta: 32767
[17:28:55] [ThaumicJEI Aspect Cache/ERROR]: Invalid BasicBlock. type: 0, meta: 32767
[17:28:56] [ThaumicJEI Aspect Cache/ERROR]: Invalid BasicBlock. type: 0, meta: 32767
[17:28:56] [ThaumicJEI Aspect Cache/ERROR]: Invalid BasicBlock. type: 0, meta: 32767
[17:29:00] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 38%
[17:29:05] [ThaumicJEI Aspect Cache/INFO]: ItemStack Aspect checking at 39%
[17:29:06] [Netty Local Client IO #0/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[17:29:06] [Netty Local Client IO #0/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[17:29:06] [Netty Local Client IO #0/INFO]: [AstralSorcery] Cleaning client cache...
[17:29:06] [Netty Local Client IO #0/INFO]: [AstralSorcery] Cleared cached client data! Disconnected from server.
```

**Comment by FallenEagle1** [comment]
It's not really an extra utilities issue, more of dealing with to much data attached to a single block, specifically in this case an inventory (rs crafting grid). I've seen this show up for other items as well, and there isn't much I know of that can be done about it. Not at a pack level at least. Last I heard it has to deal with minecraft itself.

**Comment by ogradyjd** [comment]
No worries.  I thought it might be something like that.  I just wanted to make sure you were aware of it.  Thanks!
