### ISSUE TITLE
Crash immediately upon launch

### ISSUE THREAD

**Issue by beewhisperer65** [AllTheMods/ATM-3#709]
I downloaded the 5.9.8d version on twitch, set my ram up to 6 gigs and launched the pack. It opened the launcher but when I told it to play the game, it crashed.

## Expected Behavior

It should launch like normal and continue to the mod initialization process

## Current Behavior

It crashes and says "java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:168) ~[forge-1.12.2-14.23.4.2715.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:113) ~[forge-1.12.2-14.23.4.2715.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:76) ~[forge-1.12.2-14.23.4.2715.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.4.2715.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.4.2715.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.4.2715.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.4.2715.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:163) ~[forge-1.12.2-14.23.4.2715.jar:?]
	... 2 more
[14:24:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException" in the log.

## Steps to Reproduce

1.Install pack
2.Run minecraft

## Log

https://gist.github.com/beewhisperer65/6204ae7c9c1a809cb08922985793ef9e

**Comment by Yamza** [comment]
Verify your settings align with this. https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

 If that doesn't help someone should be able to offer you other suggestions shortly.

**Comment by FallenEagle1** [comment]
To comment on this as well, I've heard of similar issues when the native launcher is used. So this issue may be tied to the version of java that minecraft is using. Looking in the log, I see java 1.8.0_51 which is quite old, so going through that picture and updating java would be a good thing to try.
