### ISSUE TITLE
PneumaticCraft drone spawned from Amadron Tablet causing crash when loading chunk

### ISSUE THREAD

**Issue by powercore2000** [AllTheMods/ATM-3#811]
## Expected Behavior
I had used the amadron tablet and was testing out the order  functions. I successfully ordered one item, a drone removed the item, but when I was to receive the reward, It caused a freeze, and now freezes once a particular chunk where the drone is located is loaded

## Current Behavior
Causes crash once chunk containing corrupted drone within is loaded, but stable if that particular chunk is not loaded. Point in crash-log where error is given:

java.lang.NullPointerException: Exception in server tick loop
	at me.desht.pneumaticcraft.common.entity.living.EntityDrone.setHandlingOffer(EntityDrone.java:1286)
	at me.desht.pneumaticcraft.common.recipes.AmadronOfferManager.tryRestockCustomOffers(AmadronOfferManager.java:120)
	at me.desht.pneumaticcraft.common.TickHandlerPneumaticCraft.tickEnd(TickHandlerPneumaticCraft.java:43)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2204_TickHandlerPneumaticCraft_tickEnd_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

## Possible Solution
Even disabling Drone AI does not stop the crash once chunk is loaded

## Log
Link: https://gist.github.com/powercore2000/e80425555d4a9795bb5c9db7cbf942e5

**Comment by FallenEagle1** [comment]
Looking through changelogs for the mod, I believe this is fixed in the newer versions of the modpack
