### ISSUE TITLE
NetworkDispatcher exception disconnects all WAN players on server

### ISSUE THREAD

**Issue by BreadDisease** [AllTheMods/ATM-3#913]
I've gotten the error "NetworkDispatcher Exception" 2 times in my ATM 3 server. When it happens, it disconnects everyone connected to the server over WAN and prints out red error text in the server console. I'm connected to the server over LAN and it doesn't disconnect me. After around 15 seconds, everyone can connect to the server again.

## Possible Solution

I've tried to read every thread I could found online, and some said to update Netty, but I don't exactly know how or if that would change anything. I've also seen that people say its due to a packet that's too big for Netty crashing it. I've also seen people saying it could be a corrupt world file, but my server works just fine after it comes back on to WAN people.

## Steps to Reproduce

No concrete steps that I've found can reproduce this. My players don't think they're doing an action that would send a packet too big either.

## Log
[debug-1.log.gz](https://github.com/AllTheMods/ATM-3/files/3523357/debug-1.log.gz)
[2019-08-20-2.log.gz](https://github.com/AllTheMods/ATM-3/files/3523358/2019-08-20-2.log.gz)

I tried to upload the logs to gist.github.com but every time I tried to publish it the page would time out. Pretty sure its because the log file is 85k lines long. Log files are attached above

## Detailed Description

My Java version is 8 Update 221 (64 bit). Server computer is running Windows 10 Pro that is on the latest updates as of 8/20/19 10:24 PM EST. No antivirus running. 10G dedicated to server with the server using about 5G. Total RAM is 16GB. Only other programs running in the background are Teamspeak 3 server and Teamviewer. I've never had this problem in the past with a minecraft server. Router is an Asus RT-AC3200 with the latest firmware. My internet speed is 500mb down 250mb up, so that shouldn't be the problem. After the first time it happened, I shut down the server, then restarted the computer the server was on. It happened again after that.

**Comment by Glendening** [comment]
```
[14:09:55] [Netty Server IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_221]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_221]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_221]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_221]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_221]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[14:09:55] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: ItsMrAwesome lost connection: Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine
[14:09:55] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: ItsMrAwesome left the game
```
